"use client";

import { useMemo, useState } from "react";
import { Search, Users, X } from "lucide-react";
import type { TVFranchisee } from "@/components/tv/touch-contact-panel";

export function FranchiseeSelector({ franchisees, selectedId, onSelect }: { franchisees: TVFranchisee[]; selectedId?: string; onSelect: (id: string) => void }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState("");
  const visible = useMemo(() => franchisees.filter(item => `${item.name} ${item.unitName}`.toLowerCase().includes(query.toLowerCase())), [franchisees, query]);
  function choose(id: string) { onSelect(id); setOpen(false); setQuery(""); }
  return <><button onClick={() => setOpen(true)} className="mt-5 flex w-full items-center justify-center gap-3 rounded-2xl bg-[#003b71] px-5 py-5 text-lg font-semibold text-white shadow-lg shadow-[#003b71]/15"><Users className="h-6 w-6 text-[#b8ee35]" />Selecionar franqueado</button>{open ? <div className="fixed inset-0 z-50 bg-[#eef7ef] p-6 lg:p-10"><div className="mx-auto flex h-full max-w-[1800px] flex-col"><header className="mb-7 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#0b8f45]">Navegação touch</p><h2 className="mt-1 text-4xl font-semibold text-[#003b71]">Selecionar franqueado</h2></div><button onClick={() => setOpen(false)} className="rounded-full border border-slate-200 bg-white p-3 text-[#003b71]"><X className="h-6 w-6" /></button></header><label className="mb-7 flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-5 py-4 shadow-sm"><Search className="h-6 w-6 text-[#0b8f45]" /><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Busque por nome ou unidade" className="w-full bg-transparent text-xl outline-none" /></label><div className="grid flex-1 auto-rows-min grid-cols-1 gap-4 overflow-y-auto pb-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map(item => <button onClick={() => choose(item.id)} key={item.id} className={`flex min-h-28 items-center gap-4 rounded-2xl border p-4 text-left transition ${item.id === selectedId ? "border-[#0b8f45] bg-[#dff3df] shadow-sm" : "border-slate-200 bg-white hover:border-[#b8ee35]"}`}><img src={item.photoUrl || "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80"} alt="" className="h-18 w-18 h-16 w-16 rounded-xl object-cover" /><span className="min-w-0"><b className="block truncate text-lg text-[#003b71]">{item.name}</b><small className="mt-1 block truncate text-sm text-slate-500">{item.unitName}</small>{item.id === selectedId ? <small className="mt-2 block font-bold text-[#0b8f45]">Em exibição</small> : null}</span></button>)}{visible.length === 0 ? <p className="col-span-full py-16 text-center text-lg text-slate-500">Nenhum franqueado encontrado.</p> : null}</div></div></div> : null}</>;
}
