import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { hashPassword, requireRole } from "@/services/auth";
const assignable=z.enum(["ADMIN","SUPPORT","TV"]);const editable=z.enum(["SUPERADMIN","ADMIN","SUPPORT","TV"]);const createSchema=z.object({name:z.string().min(2,"Informe um nome com pelo menos 2 caracteres."),email:z.string().email("Informe um e-mail válido."),password:z.string().min(8,"A senha precisa ter ao menos 8 caracteres."),role:assignable,active:z.boolean().default(true)});const updateSchema=z.object({id:z.string().min(1),name:z.string().min(2,"Informe um nome com pelo menos 2 caracteres."),email:z.string().email("Informe um e-mail válido."),role:editable,active:z.boolean(),password:z.string().min(8,"A nova senha precisa ter ao menos 8 caracteres.").optional().or(z.literal(""))});
function message(error:unknown,fallback:string){return error instanceof z.ZodError?error.issues[0]?.message||fallback:fallback}
export async function GET(){await requireRole("SUPERADMIN");return NextResponse.json(await prisma.user.findMany({select:{id:true,name:true,email:true,role:true,active:true,createdAt:true},orderBy:{name:"asc"}}));}
export async function POST(request:Request){await requireRole("SUPERADMIN");try{const p=createSchema.parse(await request.json());const user=await prisma.user.create({data:{...p,passwordHash:await hashPassword(p.password)}});return NextResponse.json(user,{status:201});}catch(error){return NextResponse.json({message:message(error,"Não foi possível criar a conta. Esse e-mail pode já estar em uso.")},{status:400});}}
export async function PUT(request:Request){await requireRole("SUPERADMIN");try{const p=updateSchema.parse(await request.json());const user=await prisma.user.update({where:{id:p.id},data:{name:p.name,email:p.email,role:p.role,active:p.active,...(p.password?{passwordHash:await hashPassword(p.password)}:{})}});return NextResponse.json(user);}catch(error){return NextResponse.json({message:message(error,"Não foi possível salvar. Verifique se o e-mail não está em uso por outra conta.")},{status:400});}}
